apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-order-system

resources:
  - namespace.yaml
  - configmap.yaml
  - infrastructure.yaml
  - migrations.yaml
  - applications.yaml

patches:
  - path: metrics-patches.yaml
  - path: migration-evidence-retention.yaml

commonLabels:
  app.kubernetes.io/part-of: go-order-management-system
  app.kubernetes.io/managed-by: kustomize
