apiVersion: batch/v1
kind: Job
metadata:
  name: identity-migrate
spec:
  ttlSecondsAfterFinished: 3600
---
apiVersion: batch/v1
kind: Job
metadata:
  name: catalog-migrate
spec:
  ttlSecondsAfterFinished: 3600
---
apiVersion: batch/v1
kind: Job
metadata:
  name: inventory-migrate
spec:
  ttlSecondsAfterFinished: 3600
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ordering-migrate
spec:
  ttlSecondsAfterFinished: 3600
