// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryReservationService_Reserve_FullMethodName = "/inventory.v1.InventoryReservationService/Reserve"
	InventoryReservationService_Confirm_FullMethodName = "/inventory.v1.InventoryReservationService/Confirm"
	InventoryReservationService_Release_FullMethodName = "/inventory.v1.InventoryReservationService/Release"
)

// InventoryReservationServiceClient is the client API for InventoryReservationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryReservationService is the contract order-service depends on to hold
// and settle stock during the order saga. It replaces the internal HTTP
// endpoints under /internal/v1/reservations and is not exposed through the API
// gateway.
//
// Callers authenticate with the shared internal service token, sent as the
// "x-internal-token" metadata key. A server configured with an empty expected
// token rejects every call.
//
// Every method is idempotent, and the saga depends on that: order-service and
// order-reconciliation-worker retry compensation indefinitely and have no way
// to tell "the call never arrived" from "the reply was lost".
type InventoryReservationServiceClient interface {
	// Reserve moves stock from available to reserved for one order.
	//
	// Idempotency is keyed on order_id, which is unique per reservation: a repeat
	// call for an order that already holds a reservation returns the existing one
	// untouched rather than reserving a second time.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Confirm settles a reservation, consuming the reserved stock permanently.
	// Calling it on an already confirmed reservation returns that reservation
	// without decrementing anything again.
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	// Release returns reserved stock to available. Calling it on an already
	// released reservation returns that reservation without incrementing again.
	//
	// Confirm and Release are terminal and mutually exclusive: a confirmed
	// reservation cannot be released, and a released one cannot be confirmed.
	// Either attempt fails with FAILED_PRECONDITION.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type inventoryReservationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryReservationServiceClient(cc grpc.ClientConnInterface) InventoryReservationServiceClient {
	return &inventoryReservationServiceClient{cc}
}

func (c *inventoryReservationServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, InventoryReservationService_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryReservationServiceClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, InventoryReservationService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryReservationServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, InventoryReservationService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryReservationServiceServer is the server API for InventoryReservationService service.
// All implementations must embed UnimplementedInventoryReservationServiceServer
// for forward compatibility.
//
// InventoryReservationService is the contract order-service depends on to hold
// and settle stock during the order saga. It replaces the internal HTTP
// endpoints under /internal/v1/reservations and is not exposed through the API
// gateway.
//
// Callers authenticate with the shared internal service token, sent as the
// "x-internal-token" metadata key. A server configured with an empty expected
// token rejects every call.
//
// Every method is idempotent, and the saga depends on that: order-service and
// order-reconciliation-worker retry compensation indefinitely and have no way
// to tell "the call never arrived" from "the reply was lost".
type InventoryReservationServiceServer interface {
	// Reserve moves stock from available to reserved for one order.
	//
	// Idempotency is keyed on order_id, which is unique per reservation: a repeat
	// call for an order that already holds a reservation returns the existing one
	// untouched rather than reserving a second time.
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Confirm settles a reservation, consuming the reserved stock permanently.
	// Calling it on an already confirmed reservation returns that reservation
	// without decrementing anything again.
	Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	// Release returns reserved stock to available. Calling it on an already
	// released reservation returns that reservation without incrementing again.
	//
	// Confirm and Release are terminal and mutually exclusive: a confirmed
	// reservation cannot be released, and a released one cannot be confirmed.
	// Either attempt fails with FAILED_PRECONDITION.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedInventoryReservationServiceServer()
}

// UnimplementedInventoryReservationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryReservationServiceServer struct{}

func (UnimplementedInventoryReservationServiceServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedInventoryReservationServiceServer) Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedInventoryReservationServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedInventoryReservationServiceServer) mustEmbedUnimplementedInventoryReservationServiceServer() {
}
func (UnimplementedInventoryReservationServiceServer) testEmbeddedByValue() {}

// UnsafeInventoryReservationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryReservationServiceServer will
// result in compilation errors.
type UnsafeInventoryReservationServiceServer interface {
	mustEmbedUnimplementedInventoryReservationServiceServer()
}

func RegisterInventoryReservationServiceServer(s grpc.ServiceRegistrar, srv InventoryReservationServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryReservationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryReservationService_ServiceDesc, srv)
}

func _InventoryReservationService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryReservationServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryReservationService_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryReservationServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryReservationService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryReservationServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryReservationService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryReservationServiceServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryReservationService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryReservationServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryReservationService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryReservationServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryReservationService_ServiceDesc is the grpc.ServiceDesc for InventoryReservationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryReservationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryReservationService",
	HandlerType: (*InventoryReservationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _InventoryReservationService_Reserve_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _InventoryReservationService_Confirm_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _InventoryReservationService_Release_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory/v1/inventory.proto",
}
